- name: install nginx and start services
  hosts: local
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: install nginx
      state: present
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes