- name: variable
  hosts: local
  connection: local
  vars: 
    Course: "DevOps with AWs"
    Duration: 120Hrs
    Traineer: "Kishor Reddy"
  tasks:
  - name: print the variable
    vars:
      course: "Ansible"
      ansible.builtin.debug: 
        msg: "Course is {{course}} Duration is {{duration}} Traineer is {{Traineer}}"