- name: variables from inventory
  hosts: local
  connection: local
  tasks:
    - name: variable
      ansible.builtin.debug:
        msg: "Course is {{course }} duration is {{ duration }} Traineer is {{Traineer}}"