- name: install nginx
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx in RHEL
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"