- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0c19f3c7a2ba2788e
    sg_id: sg-0a9984a3fd0037146
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: kommanuthala.store
    instances:
    - mysql
  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print private IP addresses
    ansible.builtin.debug:
      # msg: "Private IP of {{ item.item }}: {{ item.instances[0].private_ip_address }}"
      msg: "{{ item.instances[0].private_ip_address }}"    
    loop: "{{ ec2_info.results }}"
    when: item.instances[0].private_ip_address is defined

