- name: Create Ec2 instances and configure A record in rout53
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0c19f3c7a2ba2788e
    sg_id: sg-06664a65d9522acf5
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances: 
    - mysql
    - backend

  tasks: 
  - name: install python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip
    loop:
    - boto3
    - botocore
    
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
