- name: Create Ec2 instances and configure A record in rout53
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-07a613b1a9923cd65
    # vpc_id:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-06664a65d9522acf5 
    instance_type: t3.micro
    instances: 
    - mysql
    - backend

  tasks:
  - name: create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: " {{ sg_id }} "
      image_id: " {{ami_id}}"
      instance_type: "{{instance_type}}"
    loop: "{{ instances }}"
